name: Build And Deploy To Aliyun ECS

on:                               
  push:
    branches: [ "master" ]

jobs:                             
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest        
    steps:                        
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x' 

    - name: Install dependencies
      run: npm install --force

    - name: Build static
      run: npm run build

    - name: Deploy to tencent server        
      uses: easingthemes/ssh-deploy@v3.0.0      
      env:
        SSH_PRIVATE_KEY: ${{ secrets.BLOG_SSHKEY }} 
        ARGS: "-avzr --delete"
        SOURCE: "dist/*"
        REMOTE_HOST: ${{ secrets.BLOG_HOST }}
        REMOTE_USER: ${{ secrets.BLOG_USER }}
        TARGET: "/var/www/html/"